name: 'Jest Coverage Comment'
description: 'Comments a pull request or commit with the jest code coverage badge, full report and tests summary'
author: 'Misha Kav <misha.kav@gmail.com>'
branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: true

  title:
    description: 'Main title for the comment'
    required: false

  coverage-summary-path:
    description: 'The location of the coverage-summary of jest'
    default: './coverage/coverage-summary.json'
    required: false

  summary-title:
    description: 'Title for the coverage summary'
    default: ''
    required: false

  badge-title:
    description: 'Title for the badge icon'
    default: 'Coverage'
    required: false

  hide-summary:
    description: 'Hide coverage summary report'
    default: 'false'
    required: false

  hide-comment:
    description: 'Hide the whole comment (use when you need only `output`)'
    default: 'false'
    required: false

  create-new-comment:
    description: 'When false, will update the same comment, otherwise will publish new comment on each run'
    default: 'false'
    required: false

outputs:
  coverage:
    description: 'value indicating the coverage percentage of your report based on jest, example 78'
  color:
    description: 'color of coverage report'
  summaryHtml:
    description: 'The html of the coverage summary report (markdown table)'

runs:
  using: 'node16'
  main: 'dist/index.js'
