name: 'Jest Coverage Comment'
description: 'Comments a pull request or commit with the jest code coverage badge, full report and tests summary'
author: 'Misha Kav <misha.kav@gmail.com>'
branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub API Access Token'
    default: ${{ github.token }}
    required: true

  title:
    description: 'Main title for the comment'
    required: false

  coverage-summary-path:
    description: 'The location of the coverage-summary of jest'
    default: './coverage/coverage-summary.json'
    required: false

  summary-title:
    description: 'Title for the coverage summary'
    default: ''
    required: false

  badge-title:
    description: 'Title for the badge icon'
    default: 'Coverage'
    required: false

  hide-summary:
    description: 'Hide coverage summary report'
    default: 'false'
    required: false

  hide-comment:
    description: 'Hide the whole comment (use when you need only `output`)'
    default: 'false'
    required: false

  create-new-comment:
    description: 'When false, will update the same comment, otherwise will publish new comment on each run'
    default: 'false'
    required: false

  junitxml-path:
    description: 'The location of the junitxml path (npm package `jest-junit` should be installed)'
    default: ''
    required: false

  junitxml-title:
    description: 'Title for summary for junitxml'
    default: ''
    required: false

  coverage-path:
    description: 'The location of the coverage.txt (jest console output)'
    default: ''
    required: false

  coverage-title:
    description: 'Title for the coverage report'
    default: 'Coverage Report'
    required: false

  coverage-path-prefix:
    description: 'Prefix for path when link to files in comment'
    default: ''
    required: false

outputs:
  coverage:
    description: 'value indicating the coverage percentage of your report based on jest, example 78'
  color:
    description: 'color of coverage report'
  summaryHtml:
    description: 'The html of the coverage summary report (markdown table)'
  tests:
    description: 'Total number of tests, get from `junitxml`'
  skipped:
    description: 'Total number of skipped tests, get from `junitxml`'
  failures:
    description: 'Total number of tests with failures, get from `junitxml`'
  errors:
    description: 'Total number of tests with errors, get from `junitxml`'
  time:
    description: 'Seconds the took to run all the tests, get from `junitxml`'
  lines:
    description: 'Lines covered, get from jest text report'
  branches:
    description: 'Branches covered, get from jest text report'
  functions:
    description: 'Functions covered, get from jest text report'
  statements:
    description: 'Statements covered, get from jest text report'

runs:
  using: 'node16'
  main: 'dist/index.js'
